#!/usr/bin/env bash
# Vérifie qu'un argument a été passé et effectue 5 ping vers l'adresse IP donnée
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi
ping -c 5 "$1"
