#!/usr/bin/env bash
# Script qui modifie la résolution de localhost et facebook.com

# Création d'une sauvegarde du fichier hosts original
cp /etc/hosts /etc/hosts.bak

# Modification du fichier hosts
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts

# Ajouter ou mettre à jour l'entrée pour facebook.com
if grep -q "facebook.com" /etc/hosts; then
    # Si facebook.com existe déjà, on remplace l'entrée
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' /etc/hosts
else
    # Sinon, on ajoute une nouvelle entrée
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi